[[redirects]]
  from = "/pages/inquiries/*"
  to = "/pages/inquiries/:splat"
  force = true
  status = 200
  conditions = {Role = ["admin"]}

[[redirects]]
  from = "/.netlify/functions/getData"
  to = "/pages/inquiries/:splat"
  force = true
  status = 200
  conditions = {Role = ["admin"]}

[functions."keepAlive"]
schedule = "@daily"