# .github/workflows/keep_alive.yml

name: Keep alive cron job
on:
  schedule:
    - cron: '* * * * *' # daily https://crontab.guru/#0_12_*_*_*
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call endpoint to keep the database alive
        run: |
          curl --request GET 'ec2fix.netlify.app/.netlify/functions/keepAlive'
